### ISSUE TITLE
Warning for DVB check: Section 5.1.2 ... found avc1

### ISSUE THREAD

**Issue by gr-eurofins** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#101]
* Test: org.hbbtv_ADINS001
* File: org.hbbtv_ADINS001/ChID_voices_AVC_HD_20_64_aac.mpd

> Warning for DVB check: Section 5.1.2- 'Content SHOULD be offered using Inband storage for SPS/PPS i.e. sample entries 'avc3' and 'avc4'.', found avc1.

I'm not sure this should be a warning.

ETSI TS 103 285 V1.2.1 - 5.1.2 H.264/AVC Specifics:

Content should be offered using Inband Storage for SPS/PPS i.e. sample entries 'avc3' and 'avc4' based on
ISO/IEC 14496-15 [4]. *Content may be offered using either of the 'avc1' or 'avc2' sample entries*.

**Comment by niteeshbhat** [comment]
Resolved. In case of further inquiry, let us reopen.
