### ISSUE TITLE
WARNING: unknown mvex atom 'trep'

### ISSUE THREAD

**Issue by gr-eurofins** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#103]
* Test: org.hbbtv_APP2AV0020
* File: ADINS027.mpd

> WARNING: unknown mvex atom 'trep'

I think this is incorrect.

ISO/IEC 14496-12:2008 | 15444-12:2008 (3rd edition) / Amendment 4: MP4 files as a playlist, and large metadata support:

1.4	Movie Fragment Related

It is recognized that clients could use the Composition to Decode box (see ISO/IEC 14496-12:2008/Amd.1) to find out the required decoded picture buffering delay. However, the use of the Composition to Decode box with movie fragments is unspecified in Amendment 1.

**Comment by eceozturk** [comment]
'trep' box support is added to the segment validation software.
Related PR: #107
