### ISSUE TITLE
Validate_AVCConfigRecord: -2020

### ISSUE THREAD

**Issue by gr-eurofins** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#104]
* Test: org.hbbtv_ADINS027
* File: org.hbbtv_ADINS027/ADINS027.mpd

> ### error: moov-1:trak-1:mdia-1:minf-1:stbl-1:stsd-1 ### Validate_AVCConfigRecord: -2020"

I think this error could do with being a bit more descriptive :-)

**Comment by eceozturk** [comment]
More explanatory logs are provided. 
Related PR: #111
