### ISSUE TITLE
WARNING: unknown/unexpected atom 'hdlr'

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#115]
hdlr is not an unknown atom....

**Comment by eceozturk** [comment]
According to ISO/IEC 14496-12 Section 8.4.3.1, 'hdlr' box is contained either in 'mdia' box or 'meta' box. However this warning is coming either from 'udta' or 'minf'.

So, the warning is correctly displayed. However, more information can be given on the hierarchical location of the unkown box.

**Comment by eceozturk** [comment]
Unknown atom warning logs in the segment validation software got extended with the hierarchical path information.
Related PR: #119
