### ISSUE TITLE
WARNING on DVB/HbbTV: The fragment duration of video type (180 sec) is different from the sum of all segment durations (180 sec) in Adaptation Set: 2 Representation with 'id' : 2.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#116]
both are equal .. and still we get this....

**Comment by niteeshbhat** [comment]
Also this 
'###'HbbTV/DVB check violated: The accumulated duration of the segments [180seconds] in the representation does not match the period duration[180seconds].

http://10.4.252.64/HbbTV/org.hbbtv_00007005/00007005_1.mpd

**Comment by eceozturk** [comment]
The comparison was failing because two float values (computed differently) were being compared. Fix provided: #125
