### ISSUE TITLE
### Validate_NAL_Unit: The framerate is not matching with out of box framerate value.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#118]
the two values which doesnt match to be printed.. and instead of "out of the box"- "the MPD" should be printed

**Comment by niteeshbhat** [comment]
http://10.4.252.64/HbbTV/org.hbbtv_ADINS027/ADINS027.mpd

**Comment by eceozturk** [comment]
Log is now provided with the compared values.
Related PR: #120
