### ISSUE TITLE
crashing at subtitle rep

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#123]
http://10.4.252.64/HbbTV/org.hbbtv_DASH-ERRORREP0029/DASH-ERRORREP0029.mpd

subtitle segments are started to download, then crashes.
Works fine for audio and video

**Comment by niteeshbhat** [comment]
same here
http://10.4.252.64/HbbTV/org.hbbtv_ADINS015/ADINS015.mpd

**Comment by niteeshbhat** [comment]
here as well
 http://10.4.252.64/HbbTV/org.hbbtv_MSTRSYNC0730/org.hbbtv_MSTRSYNC0730-3.mpd

**Comment by niteeshbhat** [comment]
http://10.4.252.64/HbbTV/org.hbbtv_MSTRSYNC1755/MSTRSYNC1755.mpd

**Comment by eceozturk** [comment]
Crash was due to xml format requiring a unique root element. Fix is provided by PR #128
