### ISSUE TITLE
Unexpected box type emsg found at the begining of segment 3.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#124]
http://10.4.252.64/HbbTV/org.hbbtv_DASH-EVENT1010/DASH-EVENT1010.mpd

**Comment by eceozturk** [comment]
This error is given for the box type not being allowed to be at the beginning of a media segment. It is related to the box order. 

Concerning the support for 'emsg' box, the segment validation has a validation support for 'emsg'.

**Comment by eceozturk** [comment]
According to DASH IOP 4.2 Section 5.3.3.1: "The 'emsg' bixes shall be placed at the very beginning of the Segment [...]".
This issue is fixed by PR #146
