### ISSUE TITLE
avc3 sdtype is not evaluated

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#126]
Warning: moov-1:trak-1:mdia-1:minf-1:stbl-1:stsd-1 - unknown atom found "avcC": video sample descriptions would not normally contain this

http://10.4.252.64/HbbTV/org.hbbtv_DASH-MISC0010/DASHMISC0010.mpd

**Comment by eceozturk** [comment]
Along with avc1, avc3 further processing is provided. 
Related PR: #129
