### ISSUE TITLE
The @codecs attribute indicated for subtitles SHALL be "stpp"', not used for in Period 1 Adaptation Set 3 Representation 1.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#130]
http://10.4.252.64/HbbTV/org.hbbtv_ADINS010/ChID_voices_HEVC_HD_51_256_ddp.mpd

**Comment by eceozturk** [comment]
stpp presence check on the adaptation set level was using != instead of !==. Fix is provided by #131
