### ISSUE TITLE
For an encrypted content, ContentProtection Descriptor shall always be present and DASH264 profile shall also be present

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#137]
here, is the dash264 profile is mandatory ?
Need to be checked.

http://10.4.252.64/HbbTV/org.hbbtv_UHD-DRM-HDCP-0010/UHD-DRM-HDCP-0010.mpd

**Comment by eceozturk** [comment]
There is no clear indication on the compulsory check for dash-avc/264 profile along with content protection. But rather than removing it, it is disabled for dvb/hbbtv checks. Related PR #141
