### ISSUE TITLE
###'DVB check violated: codec in the Segment is not supported by the specification', found encv.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#138]
this error happens for encryped tracks.
When its encrypted, there is frma box which has 'hev1' codec mentioned.

So need to review this check and may be frma format need to be checked for encrypted content

http://10.4.252.64/HbbTV/org.hbbtv_UHD-DRM-HDCP-0020/UHD-DRM-HDCP-0020.mpd

**Comment by eceozturk** [comment]
Solved by PR #140
