### ISSUE TITLE
DASH264 DRM checks: No tenc found in initialization segment and also missing in media Segment 1

### ISSUE THREAD

**Issue by eceozturk** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#142]
This error is raised for encrypted content not containing any tenc box. However, this is most probably because of unnecessary processing done in HEVC NAL Unit processing function.

Needs to be investigated.

E.g.
http://10.4.252.64/HbbTV/org.hbbtv_UHD-DRM-HDCP-0010/UHD-DRM-HDCP-0010.mpd
We get this error for this test vector. However, when the NAL Unit processing call is commented out, tenc box and its parent boxes are correctly found and printed into the xml.

**Comment by niteeshbhat** [comment]
Fixed
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/167
