### ISSUE TITLE
Segment validation tool segfaults on Ubuntu 18.04

### ISSUE THREAD

**Issue by davemevans** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#149]
I have pulled the repo on 18.04 and installed dependencies as suggested in the documentation.

During testing the segment conformance tool exits with a segmentation fault on every run, regardless of the selected options.

I also rebuilt from source from the Backend repo and copied that over and still have the same problem.

Clearly it works for some people, so perhaps the documentation simply needs updating.

Any ideas?

**Comment by andyburras** [comment]
I'm finding the ISOSegementValidator sigsegv with:

> .Starting program: Conformance-and-reference-source/conformance/ISOSegmentValidator/public/linux/bin/ValidateMP4.exe -logconsole -configfile /var/www/html/dashif/Conformance-Software/webfe/temp/id1493234170/config_file.txt 
> 
> Program received signal SIGSEGV, Segmentation fault. 
> 0x5659ed74 in inflateOffset (offset64=123376) at ../src/ValidateFileIO.cpp:53

It is crashing in:
```
UInt64 inflateOffset(UInt64 offset64)                                          
{                                                                               
    UInt64 adjustedOffset = offset64;                                        
    if (vg.numOffsetEntries > 0)                                              
    {                                                                         
        unsigned int index = 0;                                                      
        for (index = 0; adjustedOffset >= vg.offsetEntries[index].offset; index++)     
        {                                                                          
            adjustedOffset += vg.offsetEntries[index].sizeRemoved; 
```


which is a very dangerous piece of code as it is relying on the data being valid to terminate the loop. In fact the the adjustedOffset = 458947329438949 so is probably corrupted from elsewhere.

Interestingly it only seems to occur if the '-logconsole' command line option is specified.

The issue also happens in the https://github.com/Dash-Industry-Forum/Conformance-Software fork.

**Comment by bbcrddave** [comment]
I get a different value of `adjustedOffset` but otherwise the exact same failure.

**Comment by niteeshbhat** [comment]
Hi, the segment validator has been built and tested on Ubuntu 16.04.
And the above segmentation fault is not observed. 
We are updating the document to mention this version as well.

**Comment by andyburras** [comment]
Looks like it is an issue with the code above. The loop always reads off the end of the malloced array, even if -logconsole is present:

> vg.numOffsetEntries= 149, index= '149'

It's just that it all depends what values happen to be in the following memory, as to whether the 'adjustedOffset >= vg.offsetEntries[index].offset' terminates the loop soon enough to prevent a crash.

**Comment by lisiensemanjaku** [comment]
Hello! The issue was observed on Ubuntu 18.xx only because the loop terminated automatically once the end of the array was reached in Ubuntu 16.xx while this did not happen in Ubuntu 18.xx. A break was introduced when the end of the array is reached : 

      for (index = 0; adjustedOffset >= vg.offsetEntries[index].offset; index++)
	         	{
		        	adjustedOffset += vg.offsetEntries[index].sizeRemoved;
                                if(index == vg.numOffsetEntries)
                                        break;
                                adjustedOffset += vg.offsetEntries[index].sizeRemoved;    
		        }

so now there is no access of out of bounds memory and the executable runs fine.  Here is the link to the changes: https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Backend/pull/37/commits/b212f48c1c395d0e09d92a481d14ffd7b93ff620
