### ISSUE TITLE
Segment conformance profile ignored

### ISSUE THREAD

**Issue by bbcrddave** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#151]
When validating a presentation advertising conformance to `urn:dvb:dash:profile:dvb-dash:isoff-ext-live:2014`, the conformance tool reports `Information on DVB-HbbTV conformance: MPD element is scoped by the profile "urn:dvb:dash:profile:dvb-dash:isoff-ext-live:2014" that the tool is not validating against`.

If the tool does not validate against either this profile (or the ondemand) variant, how can it correctly determine the segment conformance? `urn:dvb:dash:profile:dvb-dash:2014` alone is not enough - an accompanying isoff profile is required.

Example manifest: http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd

**Comment by eceozturk** [comment]
The issue is addressed. Related PR with the explanation is provided #162
