### ISSUE TITLE
Feature List highlights schema error for valid attributes, inserts attribute twice

### ISSUE THREAD

**Issue by bbcrddave** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#152]
When validating a presentation containing attributes in the namespace ` urn:dvb:dash:dash-extensions:2014-1`, the feature list page inserts those attributes twice - once in green with no `dvb:` prefix, and again in red with `dvb:` prefix, indicating a schema error.

![untitled](https://user-images.githubusercontent.com/5390145/42167334-a9bda72e-7e05-11e8-9af1-f765bb807f4a.png)

Example manifest: http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd

**Comment by eceozturk** [comment]
PR is provided #159 with the explanation of the error cause.
Closing this issue now.
