### ISSUE TITLE
Unexpected scanType error raised

### ISSUE THREAD

**Issue by bbcrddave** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#153]
When performing manifest conformance only on a presentation containing both interlaced and progressive Representations, all marked correctly with `scanType` the following error is raised:

`DVB check violated: Section 4.4- For any Representation within an Adaptation Set with @contentType="video" @scanType attribute SHALL be present if interlaced pictures are used within any Representation in the Adaptation Set`

I believe the video Representations are marked correctly, and no error should be raised. Looking at the code around the line below, I cannot work out what is going on. Note `array_unique` returns an `array` - a `count` is probably needed here, amongst other changes. https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/blob/e2cc5147a6d5fe30b50207d20cf0824e10ad1b11/webfe/MPD_HbbTV_DVB.php#L1026

Example manifest: http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-all.mpd

**Comment by eceozturk** [comment]
DVB specification Section 4.4 states that "For any Representation within an Adaptation Set with @contentType="video" the following attributes shall be present: 'scanType', if interlaced pictures are used within any Representation in the Adaptation Set". 

The fix is provided by PR #163
