### ISSUE TITLE
conformancetest.php - dxhmtltree error in firefox 61.0

### ISSUE THREAD

**Issue by andyburras** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#156]
I found I had to edit conformancetest.php and reverse these two lines, otherwise get a dxhmtltree error in firefox 61.0 -  'ReferenceError: dhtmlx is not defined dhtmlxtree.js:134:13 ' : 

    <script type="text/javascript"  src="tree/dhtmlxTree/codebase/dhtmlxtree.js"></script> 
    <script type="text/javascript" src="tree/dhtmlxTree/codebase/dhtmlxcommon.js"></script>

**Comment by eceozturk** [comment]
Suggested fix is incorporated to the code. Related PR: #161
