### ISSUE TITLE
Identical repeated errors logged causing browser to lock-up and crash

### ISSUE THREAD

**Issue by andyburras** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#157]
I ran some existing media through to check how CMAF compliant it was, which resulted in the Firefox browser locking up for a long period and then the browser tab crashing. 

The tool looks to be logging identical repeated errors for **every** chunk/segment in the media resulting in 3.3Mb Adapt0rep0log.txt and 6.8Mb Adapt1rep0log.txt.
Error reported was "Default values or per sample values SHALL be stored in each CMAF chunk's TrackFragmentBoxHeader and/or TrackRunBox ..." but I presume this could be an issue for other errors too.

When doing checking such as e.g. per segment checking then the tool needs to log only the first few occurrences and then report that further identical issues are not logged.

**Comment by niteeshbhat** [comment]
Fixed : https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/180
Now the error log is shown with only the error statement and its number of repetitions.

For ex:
(368 repetition\s) ### CMAF check violated: Section 7.5.14. "Default values or per sample values SHALL be stored in each CMAF chunk's TrackFragmentBoxHeader and/or TrackRunBox", 'description_index' not found.
