### ISSUE TITLE
Check the cross-rep log files when cmaf, dvb and hbbtv are selected.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#181]

**Comment by niteeshbhat** [comment]
When both cmaf and dvb are selected, there seems an issue with cross-rep log file and pass/fail result.
ex vector:
http://10.4.247.98/server/dash264/TestCasesHEVC/2b/16/tos_live_multires_10bit_hvc.mpd

**Comment by eceozturk** [comment]
Fix is provided by PR #182
