### ISSUE TITLE
The average segment duration is not consistent with the durations advertised by the MPD.

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#46]
This check not implemented correctly.. needs to be reviewed.
org.hbbtv_ADINS001/ChID_voices_AVC_HD_20_64_aac.mpd

**Comment by niteeshbhat** [comment]
this check removed for now.. as it falls in M2, will be reviewed and fixed.

**Comment by eceozturk** [comment]
This check is reviewed, fixed, tested and merged.
Related PR: #108
