### ISSUE TITLE
EAC3 audio channel config error

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#68]
MPD
http://10.4.252.64/HbbTV/org.hbbtv_EAC30004_NEW_URI/EAC30004_NEW_URI.mpd

Error:

'DVB check violated: Section E.2.5- For E-AC-3 the AudioChannelConfiguration element SHALL use either the "tag:dolby.com,2014:dash:audio_channel_configuration:2011" or the legacy "urn:dolby:dash:audio_channel_configuration:2011" schemeURI', conformance is not satisfied in Period 1 Adaptation Set 2 AudioChannelConfiguration

.###'DVB check violated: Section 6.3- (For E-AC-3 and AC-4 the AudioChannelConfiguration element) the @value attribute SHALL contain four digit hexadecimal representation of the 16 bit field', found "" in Period 1 Adaptation Set 2 AudioChannelConfiguration.
--

Looks like implementation problem. Because MPD is not as mentioned in error.

**Comment by eceozturk** [comment]
DVB AudioChannelConfiguration element checks for ec-3, ac-4 and dts codecs are fixed.
Related PR: #75
