### ISSUE TITLE
ContentType text error

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#69]
http://10.4.252.64/HbbTV/org.hbbtv_SUB0026/SUB0026.mpd

###'DVB check violated: Section 7.1.1- The @contetnType attribute indicated for subtitles SHALL be "text"', found as in Period 1 Adaptation Set 3 Representation 1.

Is this mandatory, bcoz contentType is not .Please check.

**Comment by eceozturk** [comment]
@contentType is an optional attribute; therefore, when checking this attribute in DVB subtitle tracks, it is first ensured that the attribute exists. 

Related PR: #73
