### ISSUE TITLE
hevc codec profile level etc error

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#71]
when codec attribute has only 'hev1',  then profile, level etc is send empty to binary file and it crashes.

http://10.4.252.64/HbbTV/org.hbbtv_MDEVSYNC205/MDEVSYNC-205.mpd

**Comment by eceozturk** [comment]
Codec processing for profile, tier and level information was missing the check if they even exist. This check is added both for HEVC and AVC codecs.

Related PR: #74
