### ISSUE TITLE
handler type 'subt' not supported

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#76]
http://10.4.252.64/HbbTV/org.hbbtv_DASH-ERRORREP0029/DASH-ERRORREP0029.mpd

### 'hdlr' handler type must be be one of ('odsm', 'crsm', 'sdsm', 'vide', 'soun', 'm7sm', 'ocsm', 'ipsm', 'mjsm', 'hint')

**Comment by niteeshbhat** [comment]
For avc3
### SampleDescription sdType must be 'mp4v', 'avc1', 'encv', 'hev1','hvc1', or 'vp09'('mp4v', 'avc1', 'encv', 'hev1','hvc1','vp09')

**Comment by niteeshbhat** [comment]
'dtse' as well

**Comment by eceozturk** [comment]
'subt' hamdler type is added.
Related PR: #82
