### ISSUE TITLE
sdType support for avc3, dtse

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#77]
For avc3

SampleDescription sdType must be 'mp4v', 'avc1', 'encv', 'hev1','hvc1', or 'vp09'('mp4v', 'avc1', 'encv', 'hev1','hvc1','vp09')

### SampleDescription sdType must be 'mp4a' or 'enca' or 'ac-4' or 'mha1' or 'ec-3' ( 'mp4a', 'enca','ac-4', 'mha1','ec-3' )

**Comment by niteeshbhat** [comment]
http://10.4.252.64/HbbTV/org.hbbtv_DASH-EVENT1010/DASH-EVENT1010.mpd

http://10.4.252.64/HbbTV/org.hbbtv_DASH-DTS001/DASH-DTS001.mpd

**Comment by eceozturk** [comment]
Addition of supported audio/video sdTypes:
- Video: avc3, avc4
- Audio: dtsc, dtsh, dtse, dtsl

Related PR: #81
