### ISSUE TITLE
Software crash due to missing if checks in content protection

### ISSUE THREAD

**Issue by eceozturk** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#96]
There needs to be checks for robustness of the software in content_protection_report(...) function.
Few examples:
- Check if the representation xml file is loaded successfully
- Check if some boxes in the xml file exists or not before trying to get an attribute from these boxes
- Test against both protected and unprotected content

**Comment by niteeshbhat** [comment]
xmlfileload from compare.php should be used.. and check if return value is not zero to continue.

**Comment by niteeshbhat** [comment]
implemented here.
https://github.com/niteeshbhat/HbbTV_DVB_Conformance_Frontend/pull/106
